# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /usr/src/app

# Set default environment variables to satisfy runtime requirements
ENV FIRECRAWL_API_KEY=firecrawl-dummy
ENV OPENAI_API_KEY=openai-dummy

# Copy package files
COPY package.json package-lock.json* ./

# Install dependencies without running scripts
RUN npm install --ignore-scripts

# Copy the rest of the application code
COPY . .

# Build the application
RUN npm run build

# Start the MCP server
CMD ["npm", "start"]
